Account settings
dk98126/mirea-bank-app pull request #10
Opened 2020-11-12 12:48 UTC by IlyaRyzhov

Добавлена возможность настраивать аккаунт пользователя. Функция findByLogin заменена функцией findByUserId.

2020-11-15 11:56 UTC, dk98126 commented on src/main/java/com/dk98126/mireabankapp/controller/MainController.java
> +        } else return "registration";
раз вот эти штуи много где повторяются, можно вынести их в отдельную функцию

2020-11-15 11:58 UTC, dk98126 commented on src/main/java/com/dk98126/mireabankapp/controller/MainController.java
> +            bindingResult.addError(fieldError);
вот это бы тоже вынести в отдельную функцию, потому что повторяется

2020-11-15 11:59 UTC, dk98126 commented on src/main/java/com/dk98126/mireabankapp/controller/MainController.java
> +            return "update-password";
мне кажется тут можно сделать PasswordException как родитель и просто передавать туда разные сообщения
потому что это вроде как плохая практика под каждую ошибку конкретную делать свое исключение

2020-11-15 12:02 UTC, dk98126 commented on src/main/java/com/dk98126/mireabankapp/model/BankUserPrincipal.java
>      public String getUsername() {
метод getUsername, а возвращает id
не очень(
плюс это еще и спринговый метод, фигово работать будет(

2020-11-15 12:04 UTC, dk98126 commented on src/main/java/com/dk98126/mireabankapp/model/form/UpdatePhoneNumberForm.java
> +    @Pattern(regexp = "^(\\+7|7|8)?[( \\-]?\\d{3}[) \\-]?\\d{3}[- ]?\\d{2}[- ]?\\d{2}$", message = "Должен быть введен номер телефона")
раз у нас много где такие паттерны используются, предлагаю сделать кастомные аннотации

2020-11-15 12:05 UTC, dk98126 commented on src/main/java/com/dk98126/mireabankapp/service/AccountRequestService.java
> +    public void createRequest(@NotNull CreateAccountRequestForm form, String userId) {
тут нужная эта аннотация @NotNull?

2020-11-15 12:11 UTC, dk98126 commented on src/main/resources/application.yml
> +      timeout: 2m
чет это постоянно меняется))

2020-11-15 12:12 UTC, dk98126 commented on src/main/resources/templates/account-settings.html
> +</html>
гитхаб подсказывает, что нужен перенос строки в конце файла

2020-11-15 12:13 UTC, dk98126 commented on src/main/resources/templates/success-update-full-name.html
> +</html>
и тут

2020-11-15 12:13 UTC, dk98126 commented on src/main/resources/templates/success-update-login.html
> +</html>
и тут

2020-11-15 12:13 UTC, dk98126 commented on src/main/resources/templates/success-update-mail.html
> +</html>
и тут

2020-11-15 12:13 UTC, dk98126 commented on src/main/resources/templates/success-update-password.html
> +</html>
и тут

2020-11-15 12:13 UTC, dk98126 commented on src/main/resources/templates/success-update-phone-number.html
> +</html>
и тут

2020-11-15 12:13 UTC, dk98126 commented on src/main/resources/templates/update-full-name.html
> +</html>
и тут

2020-11-15 12:13 UTC, dk98126 commented on src/main/resources/templates/update-login.html
> +</html>
и тут

2020-11-15 12:14 UTC, dk98126 commented on src/main/resources/templates/update-mail.html
> +</html>
и тут

2020-11-15 12:14 UTC, dk98126 commented on src/main/resources/templates/update-password.html
> +</html>
и тут

2020-11-15 12:14 UTC, dk98126 commented on src/main/resources/templates/update-phone-number.html
> +</html>
и тут

2020-11-15 12:14 UTC, IlyaRyzhov commented on src/main/java/com/dk98126/mireabankapp/controller/MainController.java
> +        } else return "registration";
Логично, что-то я ступил

2020-11-15 12:14 UTC, IlyaRyzhov commented on src/main/java/com/dk98126/mireabankapp/controller/MainController.java
> +            bindingResult.addError(fieldError);
Думаю можно

2020-11-15 12:15 UTC, IlyaRyzhov commented on src/main/java/com/dk98126/mireabankapp/controller/MainController.java
> +            return "update-password";
Согласен

2020-11-15 12:16 UTC, IlyaRyzhov commented on src/main/java/com/dk98126/mireabankapp/model/form/UpdatePhoneNumberForm.java
> +    @Pattern(regexp = "^(\\+7|7|8)?[( \\-]?\\d{3}[) \\-]?\\d{3}[- ]?\\d{2}[- ]?\\d{2}$", message = "Должен быть введен номер телефона")
Согласен

2020-11-15 12:20 UTC, IlyaRyzhov commented on src/main/java/com/dk98126/mireabankapp/service/AccountRequestService.java
> +    public void createRequest(@NotNull CreateAccountRequestForm form, String userId) {
Не уверен. Но чем плохо ее наличие?

2020-11-15 12:21 UTC, IlyaRyzhov commented on src/main/resources/templates/success-update-full-name.html
> +</html>
Не понял. Типа пустую строку в конце сделать?

2020-11-15 12:23 UTC, IlyaRyzhov commented on src/main/java/com/dk98126/mireabankapp/model/BankUserPrincipal.java
>      public String getUsername() {
Какое другое решение проблемы получения id пользователя из сессии?

2020-11-15 12:28 UTC, dk98126 commented on src/main/java/com/dk98126/mireabankapp/model/BankUserPrincipal.java
>      public String getUsername() {
находим пользователя по логину и берем его айдишник

2020-11-15 12:30 UTC, IlyaRyzhov commented on src/main/java/com/dk98126/mireabankapp/model/BankUserPrincipal.java
>      public String getUsername() {
Проблема в том, что после смены логина, в сессии остается старый логин, и мы не сможем найти айди пользователя с таким логином, так как это логина уже не существует в бд

2020-11-15 12:30 UTC, dk98126 commented on src/main/java/com/dk98126/mireabankapp/service/AccountRequestService.java
> +    public void createRequest(@NotNull CreateAccountRequestForm form, String userId) {
оно хуже не сделает, но возможно оно бесполезно
надо почитать про not null api в джаве, я тоже особо не знаю про него

2020-11-15 12:31 UTC, dk98126 commented on src/main/resources/templates/success-update-full-name.html
> +</html>
да

2020-11-15 12:40 UTC, dk98126 commented on src/main/java/com/dk98126/mireabankapp/model/BankUserPrincipal.java
>      public String getUsername() {
https://stackoverflow.com/questions/14010326/how-to-change-the-login-name-for-the-current-user-with-spring-security-3-1/14014841

2020-12-26 14:31 UTC, dk98126 requested changes
в целом вроде все норм, у меня единственное к геттерам и сеттерам вопрос

2020-12-26 14:31 UTC, dk98126 commented on src/main/java/com/dk98126/mireabankapp/model/BankUserPrincipal.java
> +    public void setLogin(String login) {
для всяких сеттеров и геттеров у нас есть ломбок)

2020-12-27 17:20 UTC, merged